"""Shared helpers for Kuraka vault scripts — ONE source of truth for project
identity and the central store layout, so every tool (init, archive, backup,
restore, discover) agrees on a project's slug and where its data lives.

No external dependencies. Importable because each script is invoked as
`python3 <vault>/<script>.py …`, which puts <vault> (this file's dir) on sys.path.

Central store layout (decided 2026-06-28 — single directory per project):

    <vault>/projects/
        INDEX.md                  rolling cross-project catalog (autogenerated)
        <slug>/
            registry.md           the project's registry note (path, stack, mode, branches)
            layer/                snapshot of the project's .claude/project/ specialization
            state/                snapshot of in-flight Kuraka artifacts (docs/process/**)
            cycles/<REQ>/         closed-cycle diagnostics (RETRO + telemetry + meta.yaml)
"""

from __future__ import annotations

import re
import shutil
import subprocess
from datetime import date
from pathlib import Path

STORE_DIRNAME = "projects"


def slugify(name: str) -> str:
    """Lowercase, hyphen-separated, alphanumeric slug."""
    s = re.sub(r"[^a-zA-Z0-9]+", "-", name).strip("-").lower()
    return s or "project"


def project_slug(project: Path, override: str | None = None) -> str:
    """Canonical slug for a project. Order of preference:
      1. explicit override (slugified),
      2. kuraka.config.yaml `project.name` (slugified),
      3. the project folder name (slugified).

    Reading `project.name` first is what keeps init/archive/backup/restore in
    agreement — keying off the folder name vs the config name was the source of
    the clinica `clinicaDental2026` vs `clinica-dental-2026` drift.
    """
    if override:
        return slugify(override)
    cfg = project / "kuraka.config.yaml"
    if cfg.exists():
        in_project = False
        for line in cfg.read_text(encoding="utf-8", errors="ignore").splitlines():
            if re.match(r"^project:\s*$", line):
                in_project = True
                continue
            if in_project:
                m = re.match(r"^\s+name:\s*(.+?)\s*$", line)
                if m:
                    return slugify(m.group(1).strip().strip("\"'"))
                if re.match(r"^\S", line):  # left the project: block
                    break
    return slugify(project.name)


def git_branch(project: Path) -> str:
    """Current git branch of the project, or a sentinel if unavailable."""
    try:
        out = subprocess.run(
            ["git", "-C", str(project), "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        if out.returncode == 0:
            return out.stdout.strip() or "(detached)"
    except (OSError, subprocess.SubprocessError):
        pass
    return "(no-git)"


# --- central store paths (all derive from one place) ---

def store_root(vault: Path) -> Path:
    return vault / STORE_DIRNAME


def project_dir(vault: Path, slug: str) -> Path:
    return store_root(vault) / slug


def registry_note(vault: Path, slug: str) -> Path:
    return project_dir(vault, slug) / "registry.md"


def layer_dir(vault: Path, slug: str) -> Path:
    return project_dir(vault, slug) / "layer"


def state_dir(vault: Path, slug: str) -> Path:
    return project_dir(vault, slug) / "state"


def cycles_dir(vault: Path, slug: str) -> Path:
    return project_dir(vault, slug) / "cycles"


def has_history(vault: Path, slug: str) -> bool:
    """True if the central store holds restorable data for this project."""
    p = project_dir(vault, slug)
    if not p.is_dir():
        return False
    return any((p / sub).is_dir() and any((p / sub).iterdir())
               for sub in ("layer", "state", "cycles"))


# --- snapshot + cycle archiving (shared by kuraka-backup / kuraka-archive) ---

def snapshot_tree(src: Path, dst: Path) -> int:
    """Mirror src into dst (copy, overwrite). Returns number of files copied.
    Used to snapshot the project's .claude/project (layer) and docs/process (state)
    into the central store. No deletes on dst beyond the subtree it owns."""
    if not src.is_dir():
        return 0
    n = 0
    for s in src.rglob("*"):
        if s.is_dir():
            continue
        rel = s.relative_to(src)
        d = dst / rel
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(s, d)
        n += 1
    return n


def find_verdict(retro_text: str) -> str:
    for pat in (r"##\s*Confidence:\s*(.+)", r"Confidence:\s*(\w+)", r"Verdict:\s*(.+)"):
        m = re.search(pat, retro_text)
        if m:
            return m.group(1).strip()[:60]
    return ""


def _retro_dirs(project: Path, docs_root: str) -> list[Path]:
    docs = project / docs_root
    candidates = [
        docs / "agent-retrospectives",
        docs / "retros",
        project / "backend" / docs_root / "agent-retrospectives",
    ]
    return [d for d in candidates if d.is_dir()]


def archive_cycles(project: Path, vault: Path, slug: str, branch: str,
                   docs_root: str, force: bool) -> list[dict]:
    """Copy each cycle's RETRO (+ telemetry) into <vault>/projects/<slug>/cycles/<REQ>/.
    Returns one row dict per cycle (status archived|skip + verdict + telem flag)."""
    today = date.today().isoformat()
    dest_root = cycles_dir(vault, slug)
    telem_dirs = [project / docs_root / "agent-telemetry",
                  project / "backend" / docs_root / "agent-telemetry"]

    retros_by_name: dict[str, Path] = {}
    for d in _retro_dirs(project, docs_root):
        for p in sorted(d.glob("RETRO-*.md")):
            if p.name == "RETRO-LATEST.md":
                continue
            retros_by_name.setdefault(p.name, p)

    rows: list[dict] = []
    for name in sorted(retros_by_name):
        retro = retros_by_name[name]
        req = retro.stem[len("RETRO-"):] if retro.stem.startswith("RETRO-") else retro.stem
        dest = dest_root / req
        if dest.exists() and not force:
            rows.append({"req": req, "status": "skip"})
            continue
        dest.mkdir(parents=True, exist_ok=True)
        retro_text = retro.read_text(encoding="utf-8", errors="ignore")
        shutil.copy2(retro, dest / retro.name)
        telem_candidates = [d / f"{req}-telemetry.json" for d in telem_dirs]
        telem_candidates.append(retro.parent.parent / "agent-telemetry" / f"{req}-telemetry.json")
        telem = next((t for t in telem_candidates if t.exists()), None)
        if telem:
            shutil.copy2(telem, dest / telem.name)
        verdict = find_verdict(retro_text)
        (dest / "meta.yaml").write_text(
            f"project: {slug}\nreq: {req}\nbranch: {branch}\narchived_at: {today}\n"
            f"source_retro: {retro}\nhas_telemetry: {str(telem is not None).lower()}\n"
            f"verdict: \"{verdict}\"\n",
            encoding="utf-8",
        )
        rows.append({"req": req, "status": "archived", "verdict": verdict,
                     "telem": telem is not None, "branch": branch})
    return rows


def update_index(vault: Path, rows: list[dict], slug: str, force: bool) -> int:
    """Append archived cycles to <vault>/projects/INDEX.md (rolling catalog)."""
    index = store_root(vault) / "INDEX.md"
    today = date.today().isoformat()
    if not index.exists():
        index.parent.mkdir(parents=True, exist_ok=True)
        index.write_text(
            "# Projects — cross-project cycle index\n\n"
            "One row per archived Kuraka cycle, across all projects. Feeds cross-project\n"
            "pattern-detection. Append-only.\n\n"
            "| Archived | Project | Cycle (REQ) | Branch | Verdict | Telemetry |\n"
            "|---|---|---|---|---|---|\n",
            encoding="utf-8",
        )
    text = index.read_text(encoding="utf-8")
    new_lines: list[str] = []
    for r in rows:
        if r["status"] != "archived":
            continue
        key = f"| {slug} | {r['req']} "
        if (key in text or any(key in nl for nl in new_lines)) and not force:
            continue
        tel = "✓" if r.get("telem") else "—"
        br = r.get("branch", "—") or "—"
        new_lines.append(
            f"| {today} | {slug} | {r['req']} | {br} | {r.get('verdict','') or '—'} | {tel} |")
    if new_lines:
        index.write_text(text.rstrip() + "\n" + "\n".join(new_lines) + "\n", encoding="utf-8")
    return len(new_lines)
