#!/usr/bin/env python3
"""kuraka-export.py — render the Kuraka workflow as portable instructions for
non-Claude-Code AI tools (Codex, Cursor, Antigravity) via AGENTS.md
(+ .cursor/rules for Cursor).

Why: Claude Code gets the full multi-subagent orchestration (mount-kuraka.sh).
Other tools don't spawn isolated subagents, so here each Kuraka agent becomes a
ROLE/persona the single agent adopts per phase, and the 8-phase discipline plus
the non-negotiable rules become a checklist in one instruction file every
AGENTS.md-aware tool reads.

Invoked via:  kuraka mount --target codex|cursor|antigravity  [dir]
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

import kuraka_common as kc

DEFAULT_VAULT = "/Users/xmn/Documents/Agentes/AgentesTrabajos/kuraka"
TARGETS = ("codex", "cursor", "antigravity")


def err(m: str) -> None:
    print(m, file=sys.stderr)


def read_agents(vault: Path) -> list[tuple[str, str]]:
    """(name, description) per vault agent, from frontmatter."""
    out = []
    adir = vault / "agents"
    for f in sorted(adir.glob("*.md")):
        text = f.read_text(encoding="utf-8", errors="ignore")
        nm = re.search(r"^name:\s*(.+)$", text, re.M)
        ds = re.search(r'^description:\s*"?(.+?)"?\s*$', text, re.M)
        name = nm.group(1).strip() if nm else f.stem
        desc = ds.group(1).strip() if ds else ""
        out.append((name, desc))
    return out


def read_config(project: Path) -> dict:
    """Best-effort parse of the few kuraka.config.yaml fields we surface."""
    cfg = project / "kuraka.config.yaml"
    d: dict = {}
    if not cfg.exists():
        return d
    top = sub = None
    for raw in cfg.read_text(encoding="utf-8", errors="ignore").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip())
        key = raw.strip().split(":", 1)[0].strip()
        val = raw.strip().split(":", 1)[1].strip().strip("\"'") if ":" in raw else ""
        if indent == 0:
            top, sub = key, None
            if val:
                d[key] = val
        elif indent == 2:
            sub = key
            if val:
                d[f"{top}.{key}"] = val
        elif indent >= 4 and top and sub:
            if val:
                d[f"{top}.{sub}.{key}"] = val
    return d


def _g(cfg: dict, *keys: str, default: str = "—") -> str:
    for k in keys:
        if cfg.get(k):
            return cfg[k]
    return default


def render_agents_md(project: Path, slug: str, cfg: dict, agents: list[tuple[str, str]]) -> str:
    backend = _g(cfg, "stack.backend.framework", "stack.backend.language")
    frontend = _g(cfg, "stack.frontend.framework")
    lang = _g(cfg, "conventions.naming_language", default="english")
    tenant = _g(cfg, "conventions.multi_tenant", default="false")
    maxf = _g(cfg, "conventions.max_file_loc", default="—")
    maxfn = _g(cfg, "conventions.max_function_loc", default="—")
    has_layer = (project / ".claude" / "project").is_dir()

    roles = "\n".join(f"| `{n}` | {d} |" for n, d in agents)

    return f"""# AGENTS.md — Kuraka workflow for `{slug}`

> Auto-generated by `kuraka mount --target …` from the Kuraka vault. Do not edit by
> hand — re-run the command to refresh. Claude Code uses the native multi-subagent
> version under `.claude/`; this file is the portable equivalent for Codex / Cursor /
> Antigravity and any other AGENTS.md-aware tool.

You are working in a project governed by **Kuraka**, a disciplined development
workflow. Other tools spawn one agent, not many — so **you adopt the relevant
*role* below per phase** and follow the gated 8-phase flow as a checklist.

## Stack

- Backend: **{backend}**  ·  Frontend: **{frontend}**
- Naming language: `{lang}`  ·  multi-tenant: `{tenant}`
- Max file LOC: `{maxf}`  ·  max function LOC: `{maxfn}`
- Full config: `kuraka.config.yaml`. {"Project-specific conventions, lessons-learned and review-checks live in `.claude/project/` — READ THEM FIRST." if has_layer else "No `.claude/project/` layer yet — run onboarding (amauta) to extract conventions."}

## How to work here — the 8-phase discipline

Run a change through these phases. Each has a **gate**: do not advance until it
passes. Scale down (skip phases) only for trivial changes, and say which you skip.

1. **PO analysis** (role `po-analyst`): restate the requirement; for external
   integrations get the **real captured contract** (payload + auth + events) —
   never invent it; classify config required-vs-defaulted.
2. **Story refinement** (role `story-refiner`): testable acceptance criteria;
   **name the mechanism** for any parse/serialize step; embed structural fixes as
   copy-this snippets, not prose; mark edge-case ACs normative vs illustrative.
3. **Test planning** (role `test-engineer`): plan happy+error+edge per function,
   a full-contract assertion, and ≥1 live-path test for external clients.
4. **Architect review + SCHEMA FREEZE** (role `architect-reviewer`): freeze the
   schema from the **observed runtime contract** (in-vivo probe), not from docs;
   run the suspect write/security path before freezing; treat every nullable
   external field as adversarial; check LOC budgets now, not at review.
5. **Implementation** (roles `backend-developer` / `frontend-developer`): one
   story at a time; **"green" = lint + typecheck + test** (a green test runner is
   NOT a clean build); commit per story.
6. **Code review** (role `code-reviewer`): 6D + the directed contract cross-check
   (implemented bodies vs frozen schema/verbatim, byte-exact); normalize external
   strings before compare; reserve BLOCKER for must-fix-now (use DEFERRED otherwise).
7. **Security review** (role `security-reviewer`): OWASP, tenant isolation, auth,
   no fail-open mock defaults in prod.
8. **Tests + E2E + deploy-verify + FINAL AUDIT** (roles `test-engineer`,
   `e2e-tester`, `deployment-verifier`, `final-auditor`): **green tests ≠ working
   feature** — run a live smoke; write a short retro of what caused rework.

### Non-negotiables (apply in every phase)
- **Observe, don't recall**: contracts/schemas/fixtures come from the running
  system or the file, never from memory. Quote `file:line` for schema claims.
- **Schema freeze before implementation** — no DB/contract changes mid-build.
- **Green build ≠ runtime-correct** — exercise the real path (a live smoke) before
  declaring done; distinguish empty-state from broken-state.
- **User approval between phases** — do not auto-advance through gates.

## Roles (adopt the mindset per phase)

| Role | What it owns |
|------|--------------|
{roles}

## Token saving

If RTK is installed for your tool, its hook compresses command output
automatically (70–90% on grep/cat/test/git). For byte-exact reads (contract
cross-checks) use `rtk proxy <cmd>` so no field is truncated.

## Project specifics

{"Read `.claude/project/conventions/*.md`, `.claude/project/lessons-learned/*.md` and `.claude/project/review-checks/*.md` — they override the generic guidance above." if has_layer else "Run the onboarding (amauta) to generate `.claude/project/` with this project's real conventions."}
"""


def render_cursor_mdc(slug: str) -> str:
    return f"""---
description: Kuraka workflow + conventions for {slug} (8-phase discipline, contract-first, green=lint+typecheck+test)
alwaysApply: true
---

# Kuraka workflow (Cursor)

Follow the full Kuraka discipline described in **`AGENTS.md`** at the repo root.
Key non-negotiables:

- Observe contracts/schemas from the running system or the file — never from memory.
- Schema freeze before implementation; no contract changes mid-build.
- "Green" = lint + typecheck + test (a green test runner is not a clean build).
- Green tests ≠ working feature — run a live smoke before declaring done.
- Adopt the relevant role per phase (po-analyst → architect-reviewer → developers
  → code-reviewer → security-reviewer → final-auditor); see AGENTS.md → Roles.
- Project-specific conventions live in `.claude/project/` — read them first.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Export Kuraka as portable AGENTS.md for non-Claude tools.")
    ap.add_argument("project", nargs="?", help="target project root")
    ap.add_argument("--project", dest="project_opt", help="target project root")
    ap.add_argument("--target", required=True, choices=TARGETS, help="codex | cursor | antigravity")
    ap.add_argument("--vault", default=os.environ.get("KURAKA_VAULT", DEFAULT_VAULT))
    ap.add_argument("--name", help="slug override")
    args = ap.parse_args()

    vault = Path(args.vault).expanduser().resolve()
    if not vault.is_dir():
        err(f"❌ vault no encontrado: {vault}")
        return 1
    project_raw = args.project_opt or args.project
    if not project_raw:
        err("❌ falta la ruta del proyecto.")
        return 1
    project = Path(project_raw).expanduser().resolve()
    if not project.is_dir():
        err(f"❌ proyecto no es un directorio: {project}")
        return 1

    slug = kc.project_slug(project, args.name)
    cfg = read_config(project)
    agents = read_agents(vault)

    print(f"🧩 kuraka export · target={args.target} · {slug}")
    agents_md = render_agents_md(project, slug, cfg, agents)
    (project / "AGENTS.md").write_text(agents_md, encoding="utf-8")
    print(f"   + AGENTS.md  ({len(agents)} roles, {len(agents_md.splitlines())} líneas)")

    if args.target == "cursor":
        rules_dir = project / ".cursor" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        (rules_dir / "kuraka.mdc").write_text(render_cursor_mdc(slug), encoding="utf-8")
        print("   + .cursor/rules/kuraka.mdc")

    if args.target == "antigravity":
        print("   ℹ️  Antigravity: se generó AGENTS.md. Verificá si tu versión también")
        print("      lee reglas de workspace propias; si es así, avisá para añadir ese target.")

    print("")
    print(f"✅ export {args.target} completo. (Claude Code sigue usando .claude/ vía 'kuraka mount'.)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
